"""Pydantic models and typed contracts shared by API routers."""

from .chat import (
    ChatHistoryResponse,
    ChatRunRequest,
    ChatStopRequest,
    ChatStopResponse,
    NormalizedChatRunRequest,
    normalize_chat_run_request,
    normalize_stop_thread_id,
)
from .sessions import (
    NormalizedSessionAutonameRequest,
    SessionAutonameRequest,
    SessionAutonameResponse,
    SessionCreateResponse,
    SessionDeleteResponse,
    SessionListResponse,
    SessionPayload,
    SessionPoolStats,
    SessionPoolStatsResponse,
    SessionTitleUpdateResponse,
    normalize_autoname_request,
)
from .skills import (
    NormalizedSkillMutationRequest,
    SkillListResponse,
    SkillModel,
    SkillMutationRequest,
    SkillMutationResponse,
    SkillPayload,
    normalize_skill_mutation_request,
)
from .system import HealthResponse, TerminalPreviewResponse
from .workspace import (
    WorkspaceDeleteResponse,
    WorkspaceFileItemPayload,
    WorkspaceMkdirResponse,
    WorkspaceReadResponse,
    WorkspaceRenameResponse,
    WorkspaceStatusResponse,
    WorkspaceUploadResponse,
)

__all__ = [
    "ChatHistoryResponse",
    "ChatRunRequest",
    "ChatStopRequest",
    "ChatStopResponse",
    "NormalizedChatRunRequest",
    "normalize_chat_run_request",
    "normalize_stop_thread_id",
    "SessionAutonameRequest",
    "SessionAutonameResponse",
    "SessionCreateResponse",
    "SessionDeleteResponse",
    "SessionListResponse",
    "NormalizedSessionAutonameRequest",
    "SessionPayload",
    "SessionPoolStats",
    "SessionPoolStatsResponse",
    "SessionTitleUpdateResponse",
    "normalize_autoname_request",
    "SkillListResponse",
    "SkillModel",
    "NormalizedSkillMutationRequest",
    "SkillMutationRequest",
    "SkillMutationResponse",
    "SkillPayload",
    "normalize_skill_mutation_request",
    "WorkspaceDeleteResponse",
    "WorkspaceFileItemPayload",
    "WorkspaceMkdirResponse",
    "WorkspaceReadResponse",
    "WorkspaceRenameResponse",
    "WorkspaceStatusResponse",
    "WorkspaceUploadResponse",
    "HealthResponse",
    "TerminalPreviewResponse",
]
